In [1]:
from scipy.optimize import linear_sum_assignment
import numpy as np

def solve_assignment_problem(cost_matrix, problem_type="balanced"):
    if problem_type == "unbalanced":
        print("Unbalanced assignment problem detected.")
        # Pad the cost matrix with zeros for unbalanced problems
        num_workers, num_tasks = cost_matrix.shape
        max_dim = max(num_workers, num_tasks)
        padded_cost_matrix = np.zeros((max_dim, max_dim))
        padded_cost_matrix[:num_workers, :num_tasks] = cost_matrix
        print("Padded cost matrix (add dummy Column):")
        print(padded_cost_matrix)
        cost_matrix = padded_cost_matrix

    # Solve the assignment problem
    row_ind, col_ind = linear_sum_assignment(cost_matrix)

    if problem_type == "unbalanced":
        # Filter out assignments to dummy tasks/workers
        valid_assignments = col_ind < cost_matrix.shape[1]  # Assuming more tasks than workers
        row_ind = row_ind[valid_assignments]
        col_ind = col_ind[valid_assignments]

        # Recalculate total cost using the original cost matrix (passed as argument)
        # to avoid including dummy costs.
        total_cost = cost_matrix[row_ind, col_ind].sum()

    else:
        # Calculate total cost for 'balanced' case (this was missing)
        total_cost = cost_matrix[row_ind, col_ind].sum()

    return row_ind, col_ind, total_cost

# Example usage with your provided matrix:
cost_matrix = np.array([[30, 39, 31, 38,40],
                        [43, 37, 32, 35,38],
                        [34, 41, 33, 41,34],
                        [39, 36, 43, 32,36],
                        [32, 49, 35, 40, 37],
                        [36, 42, 35, 44, 42]])


# Calling the correct function name: solve_assignment_problem
row_ind, col_ind, total_cost = solve_assignment_problem(cost_matrix, problem_type="unbalanced")

print("\nOptimal Assignment:")
for i in range(len(row_ind)):
    print(f"Job {row_ind[i]+1} assigned to Machine {col_ind[i]+1}")

print(f"\nMinimum Total Cost: {total_cost}")


Unbalanced assignment problem detected.
Padded cost matrix (add dummy Column):
[[30. 39. 31. 38. 40.  0.]
 [43. 37. 32. 35. 38.  0.]
 [34. 41. 33. 41. 34.  0.]
 [39. 36. 43. 32. 36.  0.]
 [32. 49. 35. 40. 37.  0.]
 [36. 42. 35. 44. 42.  0.]]

Optimal Assignment:
Job 1 assigned to Machine 3
Job 2 assigned to Machine 2
Job 3 assigned to Machine 5
Job 4 assigned to Machine 4
Job 5 assigned to Machine 1
Job 6 assigned to Machine 6

Minimum Total Cost: 166.0
