In [1]:
import numpy as np
from scipy.optimize import linprog

In [ ]:
def transportation_problem(supply, demand, costs):
    if sum(supply) != sum(demand):
        if sum(supply) < sum(demand):
            diff=sum(demand)-sum(supply)
            supply.append(diff)
            costs=np.hstack((costs,np.zeros((costs.shape[0],1))))
        else:
            diff=sum(supply)-sum(demand)
            demand.append(diff)
            costs=np.vstack((costs,np.zeros((1,costs.shape[1]))))
    num_sources=len(supply)
    num_destinations=len(demand)
    A_eq=np.zeros((num_sources+num_destinations,num_sources*num_destinations))
    for i in range(num_sources):
        A_eq[i,i*num_destinations:(i+1)*num_destinations]=1
    for j in range(num_sources,num_sources+num_destinations):
        A_eq[j,j-num_sources::num_destinations]=1
    b_eq=np.concatenate((supply,demand))
    c=costs.flatten()
    result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')
    allocation=result.x.reshape(num_sources,num_destinations)
    total_cost=result.fun
    return allocation,total_cost
supply=[30,20,50]
demand=[40,70,30]
cost=np.array([[6,8,10],[9,12,13],[14,16,18]])
allocation,total_cost=transportation_problem(supply,demand,cost)
print("Optimal Allocation:")
print(allocation)
print("Total Cost:",total_cost)


Optimal Allocation:
[[20. 10.  0.]
 [20.  0.  0.]
 [ 0. 50.  0.]
 [ 0. 10. 30.]]
Total Cost: 380.0


<ipython-input-8-7dfb4e412eda>:20: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')
<ipython-input-8-7dfb4e412eda>:20: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')


In [2]:
def transportation_problem(supply, demand, costs):
    if sum(supply) != sum(demand):
        if sum(supply) < sum(demand):
            diff=sum(demand)-sum(supply)
            supply.append(diff)
            costs=np.hstack((costs,np.zeros((costs.shape[0],1))))
        else:
            diff=sum(supply)-sum(demand)
            demand.append(diff)
            costs=np.vstack((costs,np.zeros((1,costs.shape[1]))))
    num_sources=len(supply)
    num_destinations=len(demand)
    A_eq=np.zeros((num_sources+num_destinations,num_sources*num_destinations))
    for i in range(num_sources):
        A_eq[i,i*num_destinations:(i+1)*num_destinations]=1
    for j in range(num_sources,num_sources+num_destinations):
        A_eq[j,j-num_sources::num_destinations]=1
    b_eq=np.concatenate((supply,demand))
    c=costs.flatten()
    result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')
    allocation=result.x.reshape(num_sources,num_destinations)
    total_cost=result.fun
    return allocation,total_cost
supply=[50,40,60]
demand=[30,70,50]
cost=np.array([[4,8,8],[2,7,6],[3,4,2]])
allocation,total_cost=transportation_problem(supply,demand,cost)
print("Optimal Allocation:")
print(allocation)
print("Total Cost:",total_cost)


Optimal Allocation:
[[ 0. 50.  0.]
 [30. 10.  0.]
 [ 0. 10. 50.]]
Total Cost: 670.0


<ipython-input-2-ba8d6412250b>:20: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')
<ipython-input-2-ba8d6412250b>:20: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  result=linprog(c,A_eq=A_eq,b_eq=b_eq,method='simplex')


In [3]:
import numpy as np
from scipy.optimize import linprog

def transportation_problem(supply, demand, costs):
    if sum(supply) != sum(demand):
        if sum(supply) < sum(demand):
            diff = sum(demand) - sum(supply)
            supply.append(diff)
            costs = np.hstack((costs, np.zeros((costs.shape[0], 1))))
        else:
            diff = sum(supply) - sum(demand)
            demand.append(diff)
            costs = np.vstack((costs, np.zeros((1, costs.shape[1]))))
    num_sources = len(supply)
    num_destinations = len(demand)
    A_eq = np.zeros((num_sources + num_destinations, num_sources * num_destinations))
    for i in range(num_sources):
        A_eq[i, i * num_destinations: (i + 1) * num_destinations] = 1
    for j in range(num_sources, num_sources + num_destinations):
        A_eq[j, j - num_sources::num_destinations] = 1
    b_eq = np.concatenate((supply, demand))
    c = costs.flatten()
    result = linprog(c, A_eq=A_eq, b_eq=b_eq, method='simplex')
    allocation = result.x.reshape(num_sources, num_destinations)
    total_cost = result.fun
    allocation_transposed = allocation.T
    return allocation_transposed, total_cost


supply = [30, 20, 50]
demand = [40, 70, 30]
cost = np.array([[6, 8, 10], [9, 12, 13], [14, 16, 18]])
allocation_transposed, total_cost = transportation_problem(supply, demand, cost)
print("Optimal Allocation (Transposed):")
print(allocation_transposed)
print("Total Cost:", total_cost)


Optimal Allocation (Transposed):
[[20. 20.  0.  0.]
 [10.  0. 50. 10.]
 [ 0.  0.  0. 30.]]
Total Cost: 380.0


<ipython-input-3-d221d4a0ee66>:23: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result = linprog(c, A_eq=A_eq, b_eq=b_eq, method='simplex')
<ipython-input-3-d221d4a0ee66>:23: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  result = linprog(c, A_eq=A_eq, b_eq=b_eq, method='simplex')
